### ISSUE TITLE
Compilation failed on Windows with error C2280

### ISSUE THREAD

**Issue by kapil-ms** [microsoft/snmalloc#211]
Hi

I have included the snmalloc rust crate in my project. However, I get the below error during `cargo build`.
snmalloc rust version = 0.2.13
Windows 10 version 2004
CMake version 3.17.3

```
error: failed to run custom build command for `snmalloc-sys v0.2.13`

Caused by:
  process didn't exit successfully: `D:\app\target\debug\build\snmalloc-sys-3931a9a4e61262c7\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\kapil\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\snmalloc-sys-0.2.13\\snmalloc" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DSNMALLOC_RUST_SUPPORT=ON" "-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Ob2 /DNDEBUG" "-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Ob2 /DNDEBUG" "-DCMAKE_INSTALL_PREFIX=D:\\app\\target\\debug\\build\\snmalloc-sys-9f20bc6fd3595a00\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release"
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CONST_QUALIFIED_MALLOC_USABLE_SIZE
-- Performing Test CONST_QUALIFIED_MALLOC_USABLE_SIZE - Success
-- snmalloc: Using Windows 10 APIs
-- Adding test: perf-contention-1
-- Single threaded test: perf-contention-1
-- Adding test: perf-contention-16
-- Single threaded test: perf-contention-16
-- Adding test: perf-external_pointer-1
-- Single threaded test: perf-external_pointer-1
-- Adding test: perf-external_pointer-16
-- Single threaded test: perf-external_pointer-16
-- Adding test: perf-low_memory-1
-- Single threaded test: perf-low_memory-1
-- Single threaded test: perf-low_memory-1
-- Adding test: perf-low_memory-16
-- Single threaded test: perf-low_memory-16
-- Single threaded test: perf-low_memory-16
-- Adding test: perf-singlethread-1
-- Single threaded test: perf-singlethread-1
-- Adding test: perf-singlethread-16
-- Single threaded test: perf-singlethread-16
-- Adding test: func-first_operation-1
-- Adding test: func-first_operation-16
-- Adding test: func-fixed_region-1
-- Single threaded test: func-fixed_region-1
-- Adding test: func-fixed_region-16
-- Single threaded test: func-fixed_region-16
-- Adding test: func-malloc-1
-- Adding test: func-malloc-16
-- Adding test: func-memory-1
-- Single threaded test: func-memory-1
-- Adding test: func-memory-16
-- Single threaded test: func-memory-16
-- Adding test: func-release-rounding-1 only for release configs
-- Adding test: func-release-rounding-16 only for release configs
-- Adding test: func-sizeclass-1
-- Adding test: func-sizeclass-16
-- Adding test: func-statistics-1
-- Adding test: func-statistics-16
-- Adding test: func-thread_alloc_external-1
-- Adding test: func-thread_alloc_external-16
-- Adding test: func-two_alloc_types-1
-- Single threaded test: func-two_alloc_types-1
-- Adding test: func-two_alloc_types-16
-- Single threaded test: func-two_alloc_types-16
-- Configuring done
-- Generating done
-- Build files have been written to: D:/app/target/debug/build/snmalloc-sys-9f20bc6fd3595a00/out/build
running: "cmake" "--build" "." "--target" "snmallocshim-rust" "--config" "Release" "--"
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/kapil/.cargo/registry/src/github.com-1ecc6299db9ec823/snmalloc-sys-0.2.13/snmalloc/CMakeLists.txt
  rust.cc
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\alloc.h(516): error C2280: 'snmalloc::Remote::Remote(void)': attempting to reference a deleted function [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\remoteallocator.h(36): message : compiler has generated 'snmalloc::Remote::Remote' here [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\remoteallocator.h(36,3): message : 'snmalloc::Remote::Remote(void)': function was implicitly deleted because 'snmalloc::Remote' has a variant data member 'snmalloc::Remote::next' with a non-trivial default constructor [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\remoteallocator.h(22): message : see declaration of 'snmalloc::Remote::next' [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\alloc.h(516): message : while compiling class template member function 'snmalloc::Allocator<bool snmalloc::needs_initialisation(void *),void *snmalloc::init_thread_allocator(snmalloc::function_ref<void *(void *)>),snmalloc::GlobalVirtual,snmalloc::DefaultChunkMap<snmalloc::GlobalPagemap>,true>::RemoteList::RemoteList(void)' [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\override\rust.cc(39): message : see reference to function template instantiation 'snmalloc::Allocator<bool snmalloc::needs_initialisation(void *),void *snmalloc::init_thread_allocator(snmalloc::function_ref<void *(void *)>),snmalloc::GlobalVirtual,snmalloc::DefaultChunkMap<snmalloc::GlobalPagemap>,true>::RemoteList::RemoteList(void)' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\alloc.h(543): message : see reference to class template instantiation 'snmalloc::Allocator<bool snmalloc::needs_initialisation(void *),void *snmalloc::init_thread_allocator(snmalloc::function_ref<void *(void *)>),snmalloc::GlobalVirtual,snmalloc::DefaultChunkMap<snmalloc::GlobalPagemap>,true>::RemoteList' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\alloc.h(644): message : see reference to class template instantiation 'snmalloc::Allocator<bool snmalloc::needs_initialisation(void *),void *snmalloc::init_thread_allocator(snmalloc::function_ref<void *(void *)>),snmalloc::GlobalVirtual,snmalloc::DefaultChunkMap<snmalloc::GlobalPagemap>,true>::RemoteCache' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\../ds/mpmcstack.h(14): message : see reference to class template instantiation 'snmalloc::Allocator<bool snmalloc::needs_initialisation(void *),void *snmalloc::init_thread_allocator(snmalloc::function_ref<void *(void *)>),snmalloc::GlobalVirtual,snmalloc::DefaultChunkMap<snmalloc::GlobalPagemap>,true>' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\pool.h(28): message : see reference to class template instantiation 'snmalloc::MPMCStack<T,snmalloc::PreZeroed>' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
          with
          [
              T=snmalloc::Alloc
          ]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\globalalloc.h(14): message : see reference to class template instantiation 'snmalloc::Pool<Alloc,MemoryProvider>' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]
          with
          [
              Alloc=snmalloc::Alloc,
              MemoryProvider=snmalloc::GlobalVirtual
          ]
C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\snmalloc-sys-0.2.13\snmalloc\src\mem\globalalloc.h(191): message : see reference to class template instantiation 'snmalloc::AllocPool<snmalloc::GlobalVirtual,snmalloc::Alloc>' being compiled [D:\app\target\debug\build\snmalloc-sys-9f20bc6fd3595a00\out\build\snmallocshim-rust.vcxproj]

--- stderr
CMake Warning at CMakeLists.txt:64 (message):
  Not generating clangformat target, no clang-format tool found
Call Stack (most recent call first):
  CMakeLists.txt:288 (clangformat_targets)


CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ASM_FLAGS
    CMAKE_ASM_FLAGS_RELEASE


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:885:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\io\mod.rs:1428
   5: std::sys_common::backtrace::_print
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic_handler
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:378
  11: std::panicking::begin_panic_fmt
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:332
  12: cmake::fail
             at C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:885
  13: cmake::run
             at C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:863
  14: cmake::Config::build
             at C:\Users\kapil\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:769
  15: build_script_build::main
             at .\build.rs:71
  16: std::rt::lang_start::{{closure}}<()>
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\src\libstd\rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\rt.rs:52
  18: std::panicking::try::do_call<closure-0,i32>
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:303
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libpanic_unwind\lib.rs:86
  20: std::panicking::try
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\panic.rs:394
  22: std::rt::lang_start_internal
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\/src\libstd\rt.rs:51
  23: std::rt::lang_start<()>
             at /rustc/8aa9d2014f4e5258f83b907e8431c59a33acdae7\src\libstd\rt.rs:67
  24: main
  25: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  26: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  27: BaseThreadInitThunk
  28: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by mjp41** [comment]
That has been fixed in the latest version of the crate.  Could you try 0.2.15?

**Comment by kapil-ms** [comment]
Worked. Thanks.
